mutation createFirstUser($input: UserCreateInput!) {
  createFirstUser(input: $input) {
    id
    loginName
    displayName
    email
    createdAt
    updatedAt
    posts {
      id
    }
    roles {
      id
      name
    }
  }
}

query user($input: UserWhereUniqueInput!) {
  user(input: $input) {
    id
    loginName
    displayName
    createdAt
    updatedAt
    posts {
      id
    }
    roles {
      id
      name
    }
  }
}

query users($pagination: Pagination!) {
  users(pagination: $pagination) {
    count
    edges(pagination: $pagination) {
      id
      loginName
      displayName
      createdAt
      updatedAt
      posts {
        id
      }
      roles {
        id
        name
      }
    }
  }
}

query me {
  me {
    id
    loginName
    displayName
    email
    createdAt
    updatedAt
    posts {
      id
    }
    roles {
      id
      name
    }
  }
}

mutation login($input: LoginInput!) {
  login(input: $input) {
    id
    loginName
    displayName
    email
    createdAt
    updatedAt
    posts {
      id
    }
    roles {
      id
      name
    }
  }
}

mutation updateUser($input: UserUpdateInput!) {
  updateUser(input: $input) {
    id
    loginName
    displayName
    email
    createdAt
    updatedAt
    posts {
      id
    }
    roles {
      id
      name
    }
  }
}

mutation removeUsers($input: UserWhereInput!) {
  removeUsers(input: $input) {
    count
  }
}
