query tag($input: TagWhereUniqueInput!) {
  tag(input: $input) {
    id
    slug
    name
    category {
      id
      slug
      name
      createdAt
      updatedAt
    }
    createdAt
    updatedAt
  }
}
