mutation updateTag($input: TagUpdateInput!) {
  updateTag(input: $input) {
    id
    slug
    name
    category {
      id
      slug
      name
      createdAt
      updatedAt
    }
    createdAt
    updatedAt
  }
}
