query tagCategory($input: TagCategoryWhereUniqueInput!) {
  tagCategory(input: $input) {
    id
    slug
    name
    tags {
      id
      slug
      name
      createdAt
      updatedAt
    }
    createdAt
    updatedAt
  }
}
