mutation createUser($input: UserCreateInput!) {
  createUser(input: $input) {
    id
    loginName
    displayName
    email
    createdAt
    updatedAt
    posts {
      id
    }
    roles {
      id
      name
    }
  }
}
